// database/models/alertModel.js
// Stores alerts generated by Node.js Event Emitters when metric thresholds are exceeded.

'use strict';

const mongoose = require('mongoose');

// Valid alert types matching the metric fields collected by shell scripts
const ALERT_TYPES = ['CPU', 'MEMORY', 'DISK'];

const alertSchema = new mongoose.Schema(
  {
    // Which metric triggered the alert
    type: {
      type: String,
      required: true,
      enum: ALERT_TYPES,
      uppercase: true,
    },
    // The actual metric value that triggered the alert (e.g. 92)
    value: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
    },
    // The configured threshold that was exceeded (e.g. 80)
    threshold: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
    },
    // When the alert was fired by the Event Emitter
    triggeredAt: {
      type: Date,
      default: Date.now,
    },
    // Set to true once the metric drops back below threshold
    resolved: {
      type: Boolean,
      default: false,
    },
    // Optional: timestamp when alert was resolved
    resolvedAt: {
      type: Date,
      default: null,
    },
  },
  {
    versionKey: false,
    collection: 'alerts',
  }
);

// Index for fetching unresolved alerts quickly (used by dashboard + cron jobs)
alertSchema.index({ resolved: 1, triggeredAt: -1 });

// Index for filtering by alert type (useful for dashboard charts)
alertSchema.index({ type: 1, triggeredAt: -1 });

const Alert = mongoose.model('Alert', alertSchema);

module.exports = Alert;
module.exports.ALERT_TYPES = ALERT_TYPES;
